INSERT INTO `pricearena`.`items` (`itemID`, `name`, `price`, `image`, `timesBought`) VALUES (0, 'All-new Kindle Paperwhite (8 GB) – Now with a 6.8\" display and adjustable warm light – Ad-Supported', '$139.99', '', 0),
 (1, '100Pcs Joe Biden I DID That! - Sticker Decal Humor - Joe Biden Funny Sticker That\'s All Me I Did That - Pointed to Your Left Funny Joe Biden Campaign Logo Parody Sticker 3 in', '$14.99', '', 0),
 (2, 'Philips Avent Anti-Colic Baby Bottle with AirFree Vent, 9oz, 1pk, Clear, SCY703/91', '$8.99', '', 0),
 (3, 'VELCRO Brand Extreme Outdoor Mounting Tape | 20Ft x 1 in, Holds 15 lbs | Strong Heavy Duty Stick on Adhesive | Mount on Brick, Concrete for Hanging, 30702', '$19.99', '', 0),
 (4, 'Fire TV Stick 4K streaming device with Alexa Voice Remote (includes TV controls), Dolby Vision', 'null', '', 0),
 (5, 'Madden NFL 22 - PlayStation 4', 'null', '', 0),
 (6, '2022 Planner 8\"x10\" Size: 14 Months (Begins November 2021/2022 Calendar/ 2022 Weekly Calendar/Weekly Planner Organizer (Black)', '$18.95', '', 0),
 (7, 'Introducing Fire TV Stick 4K Max streaming device, Wi-Fi 6, Alexa Voice Remote (includes TV controls)', '$54.99', '', 0),
 (8, 'Pokémon Brilliant Diamond - Nintendo Switch', '$59.88', '', 0),
 (9, '100 Pcs Forever Postage Stamps Flags', '$40.00', '', 0),
 (10, 'Interior Car Lights Keepsmile Car Accessories Car Led Lights APP Control with Remote Music Sync Color Change RGB Under Dash Car Lighting with Car Charger 12V 2A LED Lights for Car (RGB)', 'null', '', 0),
 (11, '100Pcs I Did That Biden Stickers, That\'s All Me I Did That Biden Bumper Stickers, Funny Decal Sticker Humor (A, 100 PCS)', '$9.49', '', 0),
 (12, 'Introducing Blink Video Doorbell | Two-way audio, HD video, motion and chime app alerts and Alexa enabled — wired or wire-free (Black)', '$49.99', '', 0),
 (13, 'Apple Watch Series 7 GPS, 41mm Midnight Aluminum Case with Midnight Sport Band - Regular', '$399.00', '', 0),
 (14, 'Pokémon Brilliant Diamond & Pokemon Shining Pearl Double Pack - Nintendo Switch', '$119.88', '', 0),
 (15, 'Metroid Dread - Nintendo Switch', 'null', '', 0),
 (16, 'JJHAEVDY Women\'s Bootcut Yoga Pants Crossover High Waisted Workout Leggings Stretch Non-See Through Tummy Control Flare Pants', '$17.46', '', 0),
 (17, 'New: Nano Tape – Heavy Duty Double Sided Mounting Tape – 4 Pack – Strong Grip, Removable & Reusable – 40 Feet of Clear Gel Tape for Hanging on Wood, Tile, Plastic & Metal Surfaces by Lockport', 'null', '', 0),
 (18, '2022 Pocket Planner/Pocket Calendar: Includes 14 Months (November 2021 to December 2022) / 2022 Weekly Planner/Weekly Agenda/Monthly Calendar Organizer (Black/Brown - Pack of 1)', '$9.95', '', 0),
 (19, 'Roku Streaming Stick 4K 2021 | Streaming Device 4K/HDR/Dolby Vision with Roku Voice Remote and TV Controls', '$39.99', '', 0),
 (20, 'Emerg?ncy_Keychain Car_Esc?pe Tool,2-in-1Seatbelt Cutter and Window Breaker', '$24.99', '', 0),
 (21, 'Gel Pens, Medium Point (0.7mm), Pearl White Body, Black Gel Ink Pens, 4 Count', '$3.69', '', 0),
 (22, 'LINKIOM Children\'s Padded Jacket Fashion Print Cartoon Long Collar Hooded Padded Fleece Warm Coat Winter Hoodie Outwear', 'null', '', 0),
 (23, 'Mario Party Superstars - Nintendo Switch', 'null', '', 0),
 (24, 'PediaSure Grow & Gain with 2’-FL HMO Prebiotic, Kids nutrition shake, Vitamins C, E, B1, & B2, Non-GMO, Chocolate, 8 Fl Oz Bottle, 24 Count', '$51.99', '', 0),
 (25, 'Oculus Quest 2 — Advanced All-In-One Virtual Reality Headset — 128 GB', '$299.00', '', 0),
 (26, 'ECBANLI Bracelet Car Window Breaker, Wrist Strap with Tungsten Carbide Bead Car Emergency Self Rescue Tool, Vehicle Rapid Escape Wristbands Tempered Safety Glass Breaker', '$17.99', '', 0),
 (27, '100Pcs Biden I Did That Stickers, 3inch Joe Biden Funny Sticker, That\'s All Me I Did That Decal/Humor/Funny (A, Diamond Reflective Waterproof Sticker)', '$9.97', '', 0),
 (28, 'Gskyer Telescope, 70mm Aperture 400mm AZ Mount Astronomical Refracting Telescope for Kids Beginners - Travel Telescope with Carry Bag, Phone Adapter and Wireless Remote', 'null', '', 0),
 (29, 'Security Camera 2K, blurams Baby Monitor Dog Camera 360-degree for Home Security w/ Smart Motion Tracking, Phone App, IR Night Vision, Siren, Works with Alexa & Google Assistant & IFTTT, 2-Way Audio', 'null', '', 0),
 (30, 'Amazon Basics Multipurpose Copy Printer Paper - White, 8.5 x 11 Inches, 1 Ream (500 Sheets)', '$8.99', '', 0),
 (31, 'Charmnight Womens High Waist Tights Fishnet Stockings Thigh High Pantyhose', 'null', '', 0),
 (32, 'Blink Mini – Compact indoor plug-in smart security camera, 1080 HD video, night vision, motion detection, two-way audio, Works with Alexa – 1 camera', '$34.99', '', 0),
 (33, 'Crocs Unisex-Adult Men\'s and Women\'s Classic Clog', '$43.40', 'null', 0),
 (34, 'Wyze Cam Spotlight, Wyze Cam v3 Security Camera with Spotlight Kit, 1080p HD Security Camera with Two-Way Audio and Siren, IP65 Weatherproof, Compatible with Alexa and Google Assistant', '$48.11', '', 0),
 (35, 'Microsoft 365 Personal | 12-Month Subscription, 1 person| Premium Office Apps | 1TB OneDrive cloud storage | PC/Mac Download', 'null', '', 0),
 (36, 'Rescue Monthly Whole Home Data and Image Recovery [Subscription]', 'null', '', 0),
 (37, '$10 Xbox Gift Card [Digital Code]', '$10.00', 'null', 0),
 (38, 'Scotch Heavy Duty Packaging Tape, 1.88\" x 22.2 yd, Designed for Packing, Shipping and Mailing, Strong Seal on All Box Types, 1.5\" Core, Clear, 6 Rolls with Dispenser (142-6)', '$13.99', 'null', 0),
 (39, 'McAfee Total Protection 2021, 3 Device, Antivirus Internet Security Software, VPN, Dark Web monitoring, 1 Year with Auto Renewal - Download Code', 'null', 'null', 0),
 (40, 'Roblox Gift Card - 800 Robux [Includes Exclusive Virtual Item] [Online Game Code]', '$10.00', '', 0),
 (41, 'Scotch Thermal Laminator and Pouch Bundle, 2 Roller System, Laminate up to 9\" Wide (TL901X) with Scotch Laminating Pouches, 100-Pack (TP3854-100)', 'null', 'null', 0),
 (42, 'Norton 360 for Amazon 2021 – Antivirus software for up to 3 Devices with Auto Renewal', 'null', 'null', 0),
 (43, '$10 Nintendo eShop Gift Card [Digital Code]', '$10.00', '', 0),
 (44, 'Adobe Acrobat Professional DC | Create, edit and sign PDF documents | 1-month Subscription with auto-renewal, PC/Mac', 'null', '', 0),
 (45, 'EZlifego Double Sided Tape Heavy Duty (9.85FT), Multipurpose Removable Mounting Tape Adhesive Grip,Reusable Strong Sticky Wall Tape Strips Transparent Tape Poster Carpet Tape for Paste Items,Household', '$11.99', 'null', 0),
 (46, 'Original HP 63XL Black High-yield Ink Cartridge | Works with HP DeskJet 1112, 2130, 3630 Series; HP ENVY 4510, 4520 Series; HP OfficeJet 3830, 4650, 5200 Series | Eligible for Instant Ink | F6U64AN', '$39.89', 'null', 0),
 (47, '$10 PlayStation Store Gift Card [Digital Code]', '$10.00', 'null', 0),
 (48, 'Microsoft Office Home & Student 2021 | One-time purchase for 1 PC or Mac| Download', '$124.99', '', 0),
 (49, 'Roblox Gift Card - 2000 Robux [Includes Exclusive Virtual Item] [Online Game Code]', '$25.00', '', 0),
 (50, 'WYZE Cam Outdoor Starter Bundle (Includes Base Station and 1 Camera), 1080p HD Indoor/Outdoor Wire-Free Smart Home Camera with Night Vision, 2-Way Audio, Works with Alexa & Google Assistant, white', '$58.87', '', 0),
 (51, 'Hammermill Printer Paper, 20 Lb Copy Paper, 11 x 17 - 1 Ream (500 Sheets) - 92 Bright, Made in the USA', '$15.98', '', 0),
 (52, 'Mario Party Superstars - Nintendo Switch', 'null', '', 0),
 (53, 'Ring Stick Up Cam Battery HD security camera with custom privacy controls, Simple setup, Works with Alexa - Black', '$99.99', '', 0);
